In [1]:
import torch

In [2]:
## torch.rand()

In [3]:
torch.rand(5)

tensor([0.3268, 0.5299, 0.2044, 0.8903, 0.1079])

In [4]:
torch.rand(5, 5)

tensor([[0.3744, 0.2332, 0.5606, 0.8814, 0.3150],
        [0.5972, 0.8508, 0.3069, 0.0383, 0.8616],
        [0.5521, 0.6376, 0.3351, 0.7793, 0.7234],
        [0.0399, 0.5081, 0.6472, 0.0448, 0.1905],
        [0.5502, 0.7748, 0.2056, 0.5780, 0.4646]])

In [5]:
## torch.ones

In [6]:
torch.ones(5)

tensor([1., 1., 1., 1., 1.])

In [7]:
torch.ones(5, 5)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [8]:
## torch.arange

In [9]:
torch.arange(0, 10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
## torch.tril

In [11]:
torch.tril(torch.rand(5, 5))

tensor([[0.9876, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.5992, 0.1525, 0.0000, 0.0000, 0.0000],
        [0.2030, 0.3494, 0.5286, 0.0000, 0.0000],
        [0.7856, 0.3430, 0.4145, 0.1170, 0.0000],
        [0.6553, 0.2461, 0.6781, 0.6958, 0.9038]])

In [12]:
## torch.cat

In [13]:
tensor_a = torch.tensor([[1, 2], [3, 4]])
tensor_b = torch.tensor([[5, 6], [7, 8]])

In [14]:
# Concatenate along rows
torch.cat((tensor_a, tensor_b), dim=0)

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])

In [15]:
# Concatenate along columns
torch.cat((tensor_a, tensor_b), dim=1)

tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])

In [16]:
## tensor.view()

In [17]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [18]:
x_reshaped = x.view(3, 4)
x_reshaped

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [19]:
x_reshaped.view(12)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])